abstract class TodoStates {}
class TodoInitialState extends TodoStates{}
class TodoChangeNavBarState extends TodoStates{}
class TodoChangeBottomSheetState extends TodoStates{}
class TodoCreateDBState extends TodoStates{}
class TodoGetDBState extends TodoStates{}
class TodoGetDBStateLoadingState extends TodoStates{}
class TodoInsertToDBState extends TodoStates{}
class TodoUpdateDBState extends TodoStates{}
class TodoDeleteDBState extends TodoStates{}
